import os
from dotenv import load_dotenv

# Ladataan .env-tiedosto
load_dotenv('.env')

# Telegram Botin Token ja Chat ID
TG_TOKEN = os.getenv("TG_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

# Roast-viestit
ROASTS = [
"{target}, toi heitto oli niin pitkä hauki, että se varmaan haki jo asuntoa Vaajakoskelta.",
"{target}, sun heitto ei mennyt ohi — se lähti opiskelemaan toiseen kaupunkiin.",
"{target}, jos epäonnistuminen olisi urheilulaji, sä olisit SM-tasolla.",
"{target}, toi oli hauki joka soi korvissa vielä ensi viikolla.",
"{target}, kyykät ei edes reagoinu — ne tiesi jo että sä heität ohi.",
"{target}, toi heitto kävi enemmän ilmaa kuin Linkki-linja aamuruuhkassa.",
"{target}, sun tarkkuus on kuin Jyväskylän sää — ei kukaan arvaa minne se menee.",
"{target}, toi meni niin metsään, että hirvetkin hätkähti.",
"{target}, jos hauet olis rahaa, olisit miljonääri väärällä tavalla.",
"{target}, kenttä haluais pyytää anteeksi että joutui näkemään tuon.",
"{target}, tossa ei ollu edes yritystä, pelkkää häpeää.",
"{target}, heititkö mailan vai irtosiko sulta elämästä ote?",
"{target}, jos toi oli tahallista, sun pitäisi pyytää apua.",
"{target}, toi heitto oli niin huono, että sillä vois opettaa varoittavana esimerkkinä.",
"{target}, kyykät kiitti kun et yrittänyt edes osua.",
"{target}, toi oli niin poissa linjalta, että se päätyi eri postinumeroalueelle.",
"{target}, sun heitto on kuin Keljonvaltatien liikenne — kaaos ilman syytä.",
"{target}, toi lähti niin sivuun, että se varmaan kiertää takaisin huomenna.",
"{target}, heitit hauen? Ei, sä kirjoitit romaanin epäonnistumisesta.",
"{target}, jos toi oli paras yritys, älä kerro sitä kenellekään.",
"{target}, toi ei ollu hauki vaan koko järven ekosysteemin romahdus.",
"{target}, sun heitto muistutti kesken jäänyttä remonttia — ei toimi, ei valmistu.",
"{target}, toi oli niin tyhjä heitto, että kaiku nauroi takaisin.",
"{target}, kenttä ei edes huomannu että yritit.",
"{target}, toi lähti niin vinoon, että kompastui omaan sattumaansa.",
"{target}, sun heittojen perusteella pitäis harkita näkötestiä.",
"{target}, jos tuo oli taktiikka, se oli erittäin epäterve.",
"{target}, sun heitto on yhtä johdonmukainen kuin Lutakon liikennejärjestelyt.",
"{target}, toi heitto oli niin löysä että se pyysi eläkettä.",
"{target}, hauki? Toi oli valas ja vieläpä kuollut sellainen.",
"{target}, toi heitto lensi suoraan roskakoriin — harmi että koria ei ollut.",
"{target}, sun heitot näyttää siltä että maila vihaa sua.",
"{target}, toi oli hauki josta ei voi edes vitsailla ilman sääliä.",
"{target}, mitä ikinä yritit, älä tee sitä enää.",
"{target}, toi osuu johonkin ehkä ensi viikolla.",
"{target}, sun heittojen matkareitti pitäis tulostaa kartalle turistinähtävyydeksi.",
"{target}, tää oli niin pitkä hauki että se kännykkä menetti kentät.",
"{target}, jos tää olisi tentti, saisit miinuspisteitä.",
"{target}, toi ei ollu heitto, se oli yksityinen kriisi.",
"{target}, kyykät nauroi ennen kuin maila lähti.",
"{target}, toi oli sellanen hauki, että Jyväsjärvi otti siitä itsekritiikin.",
"{target}, sä et heitä ohi — sä välttelet tarkoituksella.",
"{target}, toi feidas niin pahasti, että pitäis pyytää teatterilta apurahaa.",
"{target}, sun heitot on käyriä kuin vanha rautatie.",
"{target}, kyykät ei ole koskaan olleet noin turvassa.",
"{target}, toi oli niin etäinen heitto, että se vaatii kaukoputken.",
"{target}, sä et heitä huonosti — sun heitot on filosofisia kysymyksiä.",
"{target}, toi oli hauki joka luultavasti loukkaantui omasta suunnastaan.",
"{target}, jos kyykässä olisi varoituksia, sä olisit saanut jo neljä.",
"{target}, toi heitto unohti mitä se oli tekemässä.",
"{target}, toi oli niin paska heitto, että siitä vois järjestää seminaarin.",
"{target}, sun hauet on jo osa joukkueen traditiota.",
"{target}, toi meni niin harhaan, että siihen tarvii oppaan.",
"{target}, toi oli niin kaamea, että jopa varjo karkasi.",
"{target}, jos toi oli sun paras, en halua nähdä sun huonointa.",
"{target}, sä heitit ohi vaikka tähtäsit tyhjyyteen.",
"{target}, toi oli niin olematon, että fysiikka on pettynyt.",
"{target}, sun heitto ei ollut huono — se oli loukkaus esineheittelyä kohtaan.",
"{target}, toi oli hauki joka söi itsensä häpeään.",
"{target}, jos heitot olisivat flunssia, sä tartuttaisit koko joukkueen.",
"{target}, toi heitto eksyisi vielä sisätiloissakin.",
"{target}, sä heitit niin ohi, että edes turisti ei löytäisi perille.",
"{target}, toi lähti niin vinoon, että se kieltäytyy saamasta rakennuslupaa.",
"{target}, sun heitto oli kuin AMK:n projektiryhmä — kukaan ei tiennyt mitä tapahtuu.",
"{target}, toi hauki oli niin kylmä, että pakastinkin olisi kateellinen.",
"{target}, jos hauet olisivat pisteitä, sulla olisi miinustulos.",
"{target}, toi oli heitto, jonka perustuisi pyytämään anteeksi vanhemmilta.",
"{target}, kyykät toivoo että heität aina noin.",
"{target}, toi heitto ei tarvii selitystä, se tarvii hautajaiset.",
"{target}, sun heitto on kuin huono karaoke: pitkä, surullinen ja ohi nuotin.",
"{target}, heititkö kyykkää vai hakiko sun itsetunto uloskäyntiä?",
"{target}, toi oli hauki jolle pitäis asentaa peruutuspeili.",
"{target}, jos heittäminen olisi työ, sut irtisanottais koeajalla.",
"{target}, toi oli niin heikko, että tuuli pyysi lisää haastetta.",
"{target}, sä et heittänyt — sä päästit irti ja toivoit ihmettä.",
"{target}, toi oli hauki joka voi saada jopa järven kuivumaan häpeästä.",
"{target}, jos Jyp pelaisi noin huonosti, fanit protestois.",
"{target}, heitit varmaan vahingossa sinne missä sun motivaatio on.",
"{target}, toi hauki oli niin hidas että lumi ehtisi sulaa ja tulla takaisin.",
"{target}, toi heitto oli ohilento, ei yritys.",
"{target}, sun heitto on kuin väärä vastaus monivalinnassa.",
"{target}, toi meni niin väärään suuntaan että Google Maps luovutti.",
"{target}, jos sun heitto olis koira, se juoksis naapuriin eikä tulis takas.",
"{target}, toi oli hauki joka tekee mainehaittaa koko lajille.",
"{target}, sä heität kuin olisit allerginen osumiselle.",
"{target}, toi oli niin paska että maila otti siitä henkilökohtaisesti itseensä.",
"{target}, sun heitto on kuin huono argumentti — ei osu eikä vakuuta.",
"{target}, toi oli hauki jolla ei ole edes potentiaalia olla hyvä.",
"{target}, me ei nähty heittoa — me nähtiin epätoivoinen yritys karata.",
"{target}, kyykät kiittivät kun säästit niitä harmilta.",
"{target}, toi oli niin sivussa että se on varmaan jo toisessa pelissä.",
"{target}, jos heittäminen olis ruoka, sä tarjoilisit pelkkää käryä.",
"{target}, toi oli hauki, joka kaipaa terapiaryhmää.",
"{target}, sun heitto muistutti pajatsoon heitettyä hittiä — mutta pajatso ei ollut edes lähellä.",
"{target}, kukaan ei haluaisi myöntää tehneensä tota.",
"{target}, toi oli hauki joka ei edes yritä.",
"{target}, sä heitit kuin olisit nukahtanut kesken liikkeen.",
"{target}, toi oli hauki jonka GPS sanoi: 'en enää jaksa.'",
"{target}, sun heitoissa on sama energia kuin maanantai-aamussa.",
"{target}, toi oli heitto jonka pitäis saada kielto lähestyä kyykkiä.",
"{target}, jos epäonnistuminen olis taidetta, sä olisit galleria.",
"{target}, toi oli hauki niin pitkä, että se tarttis passin.",
"{target}, tuo heitto lähti kuin kaveri joka ei halua maksaa laskua.",
"{target}, sun heitto ei ole ongelma — se on kriisi.",
"{target}, toi osui vain siihen, että me nauretaan sulle.",
"{target}, hauki oli niin suuri, että järvi haluaisi siitä vuokraa.",
"{target}, toi heitto oli yhtä hyödyllinen kuin sateenvarjo myrskyssä.",
"{target}, sä et edes yrittänyt — ja se näky.",
"{target}, toi meni niin pahasti ohi että se voidaan laskea eri urheilulajiksi.",
"{target}, heititkö vai tiputitko epäonnistumisen?",
"{target}, toi oli hauki josta ei löydy edes tilastotietoa.",
"{target}, sun heitot on modernia taidetta — ei kukaan tajua niitä.",
"{target}, se ei ollu hauki, se oli totaalinen romahdus.",
"{target}, toi heitto oli kuin sekava sähköpostiketju — kukaan ei ymmärrä miksi se lähti.",
"{target}, sä heitit niin ohi, että naapurikenttä protestoi.",
"{target}, toi hauki oli niin iso, että sitä pitäis mitata droneilla.",
"{target}, sun heitto ei eksynyt — se juoksi pakoon.",
"{target}, toi oli hauki joka toivoi että kukaan ei huomaa sitä.",
"{target}, tää ei ollut heitto, tää oli rikos taktiikkaa vastaan.",
"{target}, tolla et osuisi edes omaan varjoosi.",
"{target}, toi oli hauki joka vois hakea turvapaikkaa.",
"{target}, jos ton vois palauttaa kauppaan, se menis suoraan alerekkiin.",
"{target}, toi oli heitto jonka tuomarikin teki mieli jättää näkemättä.",
"{target}, sun heitto oli yhtä turha kuin rikkinäinen hissi.",
"{target}, toi hauki oli niin epäonnistunut että se sais potkut kalastajalta.",
"{target}, heitit varmaan sinne missä sun motivaatio lymyilee.",
"{target}, toi oli hauki joka sai koko joukkueen hiljenemään.",
"{target}, sun heitto on niin huono, että se varmaan aiheuttaa dopplerefektin.",
"{target}, toi lähti niin väärään suuntaan että pitäis varmaan hälyttää etsintäpartio.",
"{target}, heitto näytti siltä että maila itki.",
"{target}, toi oli hauki joka tarvii oman psykoterapiasarjansa.",
"{target}, kyykät nauroi, kenttä nauroi, jopa tuuli nauroi.",
"{target}, toi heitto ei ollu huono — se oli legendaarinen katastrofi.",
"{target}, jos hauki olis henkilö, se haastais sut oikeuteen.",
"{target}, sun heitot pitäis luokitella tieliikennevaaraksi.",
"{target}, toi oli hauki jonka näkeminen vähensi mun elinvuosia.",
"{target}, heitit varmaan sinne missä sun järki kävi viimeksi.",
"{target}, toi oli sellanen hauki että se vaatii erillisen raportin.",
"{target}, sun heitto ei menny ohi, se pakeni.",
"{target}, toi oli hauki jolla on oma kiertorata.",
"{target}, sun heitto oli niin huono että maapallo kääntyi pois.",
"{target}, toi oli hauki joka ei onnistuisi edes kalastussimulaatiossa.",
"{target}, jos heittäminen olisi rikos, saisit elinkautisen.",
"{target}, toi ei ollu hauki, se oli kansallinen kriisi.",
"{target}, sun heitto on kuin vanha puhelin — ei toimi kun tarvitsisi.",
"{target}, toi meni niin ohi että kehitys kehottaa lopettamaan.",
"{target}, heititkö kyykkää vai heivasitko toivon menemään?",
"{target}, toi hauki oli niin väärä että GPS halus palauttaa sen.",
"{target}, sun heitto oli tyhjempi kuin kyykkäkenttä juhannuksena.",
"{target}, toi heitto oli niin järkyttävä, että koko kenttä mietti pitäisikö sun saada heittokielto.",
"{target}, toi ei ollut hauki — se oli täysi romahdus, josta YT-neuvottelutkin olis kateellisia.",
"{target}, sun heitto oli niin paska, että maila varmaan yrittää irtautua omistajuussuhteesta.",
"{target}, toi lähti niin vinoon, että jopa fyysikot koki eksistentiaalikriisin.",
"{target}, sä heitit niin ohi, että kyykät nosti kädet ylös ja sanoi 'me ei voida auttaa'.",
"{target}, toi oli hauki joka kuolis häpeästä jos sillä olis tunteet.",
"{target}, jos sun heitolla olis ääni, se huutais apua.",
"{target}, toi oli niin susi heitto, että metsästäjätkin karttais sitä.",
"{target}, sun heitot on sellasia, että GPS ei suostu edes reitittämään niitä.",
"{target}, toi oli hauki, joka sais potkut kalastajalta TRAFI:n tarkastuksessa.",
"{target}, toi lähti niin väärään suuntaan, että olis helpompi sanoa missä se EI käynyt.",
"{target}, sun heitto oli henkinen liikenneonnettomuus.",
"{target}, toi hauki oli niin iso katastrofi, että vakuutusyhtiöt lisäis varmuusmaksun.",
"{target}, heititkö oikeasti vai yrititkö piilottaa itsesi kyykiltä?",
"{target}, toi oli hauki, joka rikkois mittalaitteet jos sitä yrittäis mitata.",
"{target}, sun heitto oli niin tyhjä, että jopa kaiku häpesi vastata.",
"{target}, toi meni niin ohi, että joku vois soittaa hätänumeroon.",
"{target}, sä heität kuin olisit kemiallisessa sodassa osumista vastaan.",
"{target}, toi heitto oli niin kelvoton, että sääntöjen pitäisi muuttua ihan vain sua varten.",
"{target}, jos heittäminen olisi tentti, tää olis kirjattu 'katastrofaalinen epäonnistuminen'.",
"{target}, toi hauki ei oo pelkkä ohiheitto — se on moraalinen varoitus.",
"{target}, sun heitto lähti niin päin helvettiä, että itse helvettikin jäi kysymysmerkiksi.",
"{target}, toi oli hauki joka ansaitsisi elämäkerrasta nimen 'Näin ei heitetä'.",
"{target}, jos tää olisi haaste, sä saisit kieltoa jatkaa yrittämistä.",
"{target}, toi heitto oli niin ruma, että maaperä loukkaantui.",
"{target}, sä teit niin suuren hauen, että geologit halus tutkia sen.",
"{target}, toi ei mennyt ohi — se teleporttasi toiseen ulottuvuuteen häpeästä.",
"{target}, sun heitto on kuin lupaus joka petettiin välittömästi.",
"{target}, toi oli hauki joka räjäyttäisi koko ottelun uskottavuuden.",
"{target}, sä heität kuin maila yrittäisi paeta sua.",
"{target}, toi heitto oli niin hukassa, että poliisi ei edes yrittäisi etsiä sitä.",
"{target}, tuo hauki ei ollut pelkkä ohiheitto — se oli lajin solvaus.",
"{target}, sun heitto kuoli matkalle.",
"{target}, toi oli niin massiivinen epäonnistuminen, että sitä vois opettaa korkeakoulussa.",
"{target}, sun heitto oli kuin rikottu ikkuna — kaikki tietää että joku mokasi pahasti.",
"{target}, toi hauki oli niin pitkä, että edes valonnopeus ei pysyis siinä perässä.",
"{target}, heitit niin pieleen, että maila epäilee sun motiiveja.",
"{target}, toi oli hauki joka pitäis lähettää tutkittavaks: 'miten näin paskasti edes onnistuu?'",
"{target}, sun heitto oli niin heikko, että se varmaan pyysi armoa.",
"{target}, toi ei ollut hauki, se oli vastalause koko lajille.",
"{target}, sun heitot on kuin sysipimeä syksy – loputonta masennusta ja eksymistä.",
"{target}, toi lähti niin sivuun että Maanmittauslaitos haluis tehdä siitä uuden karttalehden.",
"{target}, sun heitto oli niin raaka pettymys, että pelivälineet pohtii eläkkeelle jäämistä.",
"{target}, toi hauki oli niin törkeä, että sen vois kriminalisoida.",
"{target}, sä heitit niin huonosti, että jopa tuuli halus lakata puhaltamasta.",
"{target}, toi heitto teki enemmän tuhoa kuin itse osuma vois koskaan.",
"{target}, sun hauet ei ole pelkästään ohiheittoja — ne on moraalinen romahdus."
]


